Add Spring Boot Data JPA part
OlesiaKapustynska/book-store pull request #3
Opened 2024-02-15 22:40 UTC by OlesiaKapustynska

2024-02-16 11:46 UTC, yevheniisynytsia requested changes
Great job! Left some minor comments to improve the solution

2024-02-16 11:46 UTC, yevheniisynytsia commented on pom.xml
> +			<version>${liquibase.version}</version>
do you have `${liquibase.version}` defined in the `<properties>` block?

2024-02-16 11:46 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstore/repository/BookRepository.java
>      Book save(Book book);
please remove custom methods, they will be accessible by default after extending `JpaRepository`

2024-02-16 11:46 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
```suggestion
                    primaryKey: true
```
primaryKey is nonnull by default

2024-02-16 11:46 UTC, yevheniisynytsia commented on src/main/java/com/example/bookstore/repository/BookRepository.java
> +@Repository
tip: `@Repository` is not necessary if you extend `JpaRepository`, but you may leave it if you want

2024-02-16 12:38 UTC, OlesiaKapustynska commented on pom.xml
> +			<version>${liquibase.version}</version>
in spring-boot-dependencies

2024-02-27 09:51 UTC, yevheniisynytsia approved these changes
🔥

2024-02-27 14:28 UTC, merged